apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:8.15.4-ce.1
        imagePullPolicy: Always
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url "http://gitlab.example.com"
            postgresql['enable']=false
            gitlab_rails['db_host'] = 'gitlab-postgresql'
            gitlab_rails['db_password']='+BP52QIxpT/flVCMpL3KXA=='
            gitlab_rails['db_username']='gitlab'
            gitlab_rails['db_database']='gitlab_production'
            redis['enable'] = false
            gitlab_rails['redis_host']='gitlab-redis'
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        livenessProbe:
          httpGet:
            path: /help
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /help
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-rails-storage
